config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # hide crud rails routes for non-json request
  constraints ->(request) { request.format == :json } do
    # ... routes
    get '/profile', to: 'profile#show', as: :profile
    resources :day_works, only: [:update]
    resources :works, only: [:index, :create, :update] do
      resources :day_works, only: [:index, :create, :update] do
        get '/:day', to: 'day_works#show', on: :collection
      end
    end
  end

  # all requests receiving vue app
  root 'home#index'
  get '/*slug', to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      @user = user
      user_abilities
    else
      guest_abilities
    end
  end

  private

  def guest_abilities; end

  def user_abilities
    can :manage, @user
    can :manage, Work, user_id: @user.id
    can :manage, DayWork, work: { user_id: @user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/day_result.rb
class DayResult < ApplicationRecord
end

app/models/day_work.rb
class DayWork < ApplicationRecord
  validates :day, presence: true, uniqueness: { scope: [:work_id] }
  belongs_to :work

  before_validation :calc_points, on: :update
  # after_commit :update_next_day,  on: :update

  def calc_points
    self.points = work.calc_points(result)
  end

  # def update_next_day
  #   next_day_works.first.update(prev_points: total_points) if next_day_works.first
  # end

  def next_day_works
    work.day_works.where("day > ?", day).order(:day)
  end

  def check_undone!
    self.update(points: work.calc_points(0), result: 0) if (result == -1) && (day < Date.current)
  end

  def self.unchecked(day = Date.current)
    where("day < ? AND result = -1", day)
  end

  def total_points
    pp = prev_points || 0
    p  = points      || 0
    pp + p
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works
  has_many :day_results
end

app/models/work.rb
class Work < ApplicationRecord
  validates :title, presence: true

  belongs_to :category, optional: true
  belongs_to :user
  has_many :day_works, dependent: :destroy

  extend Enumerize
  enumerize :frequency_type, :in => {
    every_day:   1,
    every_week:  2,
    every_month: 3,
    in_week:     4,
    in_month:    5
  }


  FAIL_DAY_POINTS = -1
  DAY_POINTS = 1.0


  before_validation :check_params
  after_commit :create_day_works

  def check_params
    self.frequency = 1  if frequency.nil? || frequency == 0
    self.complexity = 1 if complexity.nil? || complexity == 0
  end

  def last_day_works(count=1)
    day_works.where("day <= ?", Date.current).order(:day).last(count)
  end
  
  def create_day_works(range = nil)
    range = get_creation_range if range == nil

    last_dw = day_works.order(:day).last

    range.each do |day|
      DayWork.create(
        day: day,
        work: self,
        result: -1,
        points: day < Date.current ? Work::FAIL_DAY_POINTS : 0,
        prev_points: last_dw ? last_dw.prev_points + last_dw.points : 0
      )
    end
  end

  def get_creation_range
    last_dw = day_works.order(:day).last
    start = last_dw ? last_dw.day + 1.day : Date.current
    finish = Date.current + 1.month
    start..finish
  end

  def calc_points(result)
    result = result.to_i
    return Work::FAIL_DAY_POINTS if result == 0
    return base_points     if result == 1
    return base_points + 2 if result == 2
    return base_points + 4 if result == 3
    0
  end

  def base_points
    self.frequency = 1 if self.frequency.nil? || self.frequency < 1
    return Work::DAY_POINTS * self.frequency * complexity      if frequency_type == 'every_day'
    return Work::DAY_POINTS * self.frequency * complexity * 7  if frequency_type == 'every_week'
    return Work::DAY_POINTS * self.frequency * complexity * 30 if frequency_type == 'every_month'
    return Work::DAY_POINTS / self.frequency * complexity * 7  if frequency_type == 'in_week'
    return Work::DAY_POINTS / self.frequency * complexity * 30 if frequency_type == 'in_month'
    0
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

end

app/controllers/day_works_controller.rb
class DayWorksController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def index
    authorize! :index, DayWork
    @day_works = DayWork.accessible_by(current_ability)
    render json: DayWorkSerializer.new(@day_works).serializable_hash.to_json, status: :ok
  end

  def show
    @day_work = DayWork.where(day: params[:day].to_date, work_id: params[:work_id]).first
    authorize! :show, @day_work
    render json: DayWorkSerializer.new(@day_work).serializable_hash.to_json, status: :ok
  end

  def create
    authorize! :create, DayWork
    @day_work = DayWork.create(day_work_params.merge(user: current_user))
    if @day_work.errors.empty?
      render json: DayWorkSerializer.new(@day_work).serializable_hash.to_json, status: :ok
    else
      render json: @day_work.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  def update
    @day_work = DayWork.find(params[:id])
    authorize! :update, @day_work
    if @day_work.update(day_work_params)
      render json: DayWorkSerializer.new(@day_work).serializable_hash.to_json, status: :ok
    else
      render json: @day_work.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  private

  def day_work_params
    params.require(:day_work).permit( :result )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  respond_to :json
  def show
    render json: ProfileSerializer.new(current_user).serializable_hash.to_json, status: 200
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def index
    authorize! :index, Work
    @works = Work.accessible_by(current_ability)
    render json: WorkSerializer.new(@works).serializable_hash.to_json, status: :ok
  end

  def create
    authorize! :create, Work
    @work = Work.create(work_params.merge(user: current_user))
    if @work.errors.empty?
      render json: WorkSerializer.new(@work).serializable_hash.to_json, status: :ok
    else
      render json: @work.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  def update
    @work = Work.find(params[:id])
    authorize! :update, @work
    if @work.update(work_params)
      render json: WorkSerializer.new(@work).serializable_hash.to_json, status: :ok
    else
      render json: @work.errors.full_messages.to_json, status: :unprocessable_entity
    end
  end

  private

  def work_params
    params.require(:work).permit(
      :title,
      :complexity,
      :category_id,
      :frequency_type,
      :frequency,
      :desc_10,
      :desc_50,
      :desc_100,
      :finished,
      :started,
      :start_date,
      :finish_date,
      :icon,
      :color
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
/h1 Sanddays

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title SandDays Calendars
    link rel="preconnect" href="https://fonts.gstatic.com"
    link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&display=swap" rel="stylesheet"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body
    div id="app"
      - if user_signed_in?
        app
      = yield

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <span>Уже есть аккаунт? </span>
  <%= link_to "Войти", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <span>Нет аккаунта? </span>
  <%= link_to "Создать", new_registration_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
<!--  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<%# end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>